name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GENIUSTOKEN: ${{ secrets.GENIUSTOKEN }}
          LAVALINK_TOKEN: ${{ secrets.LAVALINK_TOKEN }}
          LAVALINK_EMAIL: ${{ secrets.LAVALINK_EMAIL }}
          LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TRACKERGG: ${{ secrets.TRACKERGG }}
          RIOTTOKEN: ${{ secrets.RIOTTOKEN }}
          GHUBTOKEN: ${{ secrets.GHUBTOKEN }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
          PATCHES_CHANNEL: ${{ secrets.PATCHES_CHANNEL }}
          CASH: ${{ secrets.CASH }}

      - name: Cleanup Unused Images
        run: docker image prune -f